networks:
  frontend:
    external: true
services:
  portainer:
    container_name: portainer
    image: portainer/portainer-ce:latest
    volumes:
      - data:/data
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      TZ: 'Europe/Amsterdam'
      NETWORK_ACCESS: internal
    restart: unless-stopped
    networks:
      - frontend
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.portainer.entrypoints=http"
      - "traefik.http.routers.portainer.rule=Host(`portainer.homelab.dzarpelon.com`)"
      - "traefik.http.middlewares.portainer-https-redirect.redirectscheme.scheme=https"
      - "traefik.http.routers.portainer.middlewares=portainer-https-redirect"
      - "traefik.http.routers.portainer-secure.entrypoints=https"
      - "traefik.http.routers.portainer-secure.rule=Host(`portainer.homelab.dzarpelon.com`)"
      - "traefik.http.routers.portainer-secure.tls=true"
      - "traefik.http.routers.portainer-secure.service=portainer"
      - "traefik.http.services.portainer.loadbalancer.server.port=9000"
      - "traefik.docker.network=frontend"
volumes:
  data:
